server:
  port: 8081
spring:
  redis:
    database: 1
    host: 127.0.0.1
oauth2-resource:
  enabled: true
  client-id: cdb
  client-secret: cdb
  token-endpoint: http://localhost:8080/oauth/token
  check-token-endpoint: http://localhost:8080/oauth/check_token
logging.level.org.springframework.web.client: debug