server:
  port: 8088

logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    host: localhost
    port: 6379
    database: 0