spring:
  redis:
    database: 1
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/org?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
wechat:
  client:
    clientId: [your app id]
    clientSecret: [you app secret]
    accessTokenUri: https://qyapi.weixin.qq.com/cgi-bin/gettoken
    userAuthorizationUri: https://open.weixin.qq.com/connect/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: snsapi_userinfo
  resource:
    userInfoUri: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
logging.level.org.springframework.security: debug
logging.level.org.springframework.security.oauth2: debug