@startuml
interface AuthenticationManager {
    Authentication authenticate(Authentication authentication);
}

class OAuth2AuthenticationManager implements AuthenticationManager{
    Authentication authenticate(Authentication authentication);
}
@enduml