spring:
  security:
    oauth2:
      client:
        registration:
          highzap:
            client-id: highzap_cloud
            client-secret: highzap_cloud
        provider:
          highzap:
            authorization-uri: http://localhost:8088/oauth2/v1/authorize
            token-uri: http://localhost:8088/oauth2/v1/token
            user-info-uri: http://localhost:8088/oauth2/v1/userinfo
  application:
    name: oauth2-client-sampleoauth2

server:
  port: 9000

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          oauth2: DEBUG
