server:
  port: 8089
spring:
  redis:
    database: 0
    host: 127.0.0.1
oauth2-resource:
  enabled: true
  client-id: cdb
  client-secret: cdb
  token-endpoint: http://localhost:8088/oauth/token
  check-token-endpoint: http://localhost:8088/oauth/check_token

logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
        web:
          client: DEBUG